name: ThatHurts
version: '${version}'
main: me.comfortable_andy.thathurts.ThatHurtsMain
api-version: 1.20
authors: [Comfortable_Andy]
permissions:
  thathurts.commands.boundingboxtest:
    default: op
  thathurts.commands.plugin:
    default: op